spring.application.name=gemora-server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/gemora_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Sandu@123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT configuration
jwt.secret=GemoraSecureKey_2025_JWT_Auth_Token_For_Backend!
jwt.expiration-ms=360000000000 

# Debug Spring Security decisions
logging.level.org.springframework.security=DEBUG

#  assuming your uploads folder is in your project root
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
spring.mvc.static-path-pattern=/uploads/**
